# Generated by Django 3.1.2 on 2021-01-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mecanica', models.IntegerField()),
                ('Teleccom', models.IntegerField()),
                ('Dibujo', models.IntegerField()),
                ('Diseno', models.IntegerField()),
                ('Fundicion', models.IntegerField()),
                ('Electronica', models.IntegerField()),
                ('Electricidad', models.IntegerField()),
                ('Pregunta', models.TextField()),
                ('Respuesta_Co', models.TextField()),
                ('Tipo', models.TextField()),
                ('Respuestas', models.TextField()),
            ],
        ),
    ]
