# Generated by Django 3.1.2 on 2021-01-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacion', '0002_preguntas'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='NumPreg',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
